basePath: /
definitions:
  domain.Product:
    properties:
      description:
        example: Uma mesa, como outra qualquer
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Mesa
        type: string
      price:
        example: 200
        type: number
    type: object
host: localhost:3000
info:
  contact:
    name: Keven Lopes
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Clean GO API Docs
  version: 1.0.0
paths:
  /product:
    get:
      consumes:
      - application/json
      description: Fetch products with server pagination
      parameters:
      - description: 1,2
        in: query
        name: sort
        required: true
        type: string
      - description: true,false
        in: query
        name: descending
        required: true
        type: string
      - description: "1"
        in: query
        name: page
        required: true
        type: integer
      - description: "10"
        in: query
        name: itemsPerPage
        required: true
        type: integer
      - description: 1,2
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Product'
      summary: Fetch products with server pagination
      tags:
      - product
    post:
      consumes:
      - application/json
      description: Create new product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Product'
      summary: Create new product
      tags:
      - product
swagger: "2.0"
